[package]
name = "ice40"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
log = "0.4"
hashers = "1.0.1"
#ordered-float = "3.2.0"
thiserror = "1.0"
#bitvec = "1.0.1"
